version: "3.8"
services:
  ds-tgtrack:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app/public
      - ./models:/app/models
    env_file:
      - .env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-db: